compressionLevel: 0

enableGlobalCache: false

nmMode: hardlinks-local
# This ensures that node-modules are set up
# with PnP (plug and play) amd create a node-modules file instead of
# .pnp.cjs
nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

