import type { Metadata } from "next";
import { getAppFontVariables } from "@kavita-likes-fajitas/fonts";
import "./globals.css";
import clsx from "clsx";
import { NavBar } from "@kavita-likes-fajitas/ui-library/NavBar";

import navLinks from "../public/navLinks.json";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontVariables = getAppFontVariables();
  return (
    <html lang="en">
      <body className={clsx(fontVariables, "antialiased")}>
        <NavBar navLinks={navLinks.navLinks} />
        {children}
      </body>
    </html>
  );
}
