name: "Living Kavita Loca App Tests, Build, Lint and Check Size - Reusable Workflow"

on: workflow_call

jobs:
  build-app-and-run-tests:
    environment: default
    name: "Living Kavita Loca App Tests, Build, Lint and Check Size"
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: apps/living-kavita-loca

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: ⏩ Cache turbo build setup
        uses: actions/cache@v4
        with:
          path:
            .turbo
            # TODO: sha may changes on every commit, may need to modify this
          key: ${{ runner.os }}-turbo-portfolio-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-portfolio-

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-monorepo-install

      - name: ♻️ Restore living-kavita-loca related caches
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/apps/living-kavita-loca/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: living-kavita-loca-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: 📝 Generate Next.js types
        run: yarn next typegen

      - name: 🕵️ Typecheck
        run: yarn --top-level run turbo typecheck

      - name: 🔬 Linter
        run: yarn --top-level run turbo lint
        env:
          TIMING: 1

      - name: 🧪 Unit tests
        run: yarn --top-level run turbo test-ci

      - name: 🏗 Build living-kavita-loca
        run: yarn --top-level run turbo build
        env:
          NEXT_TELEMETRY_DISABLED: true
          ENABLE_CACHE: true

      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: 🚀 Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync out s3://${{ vars.S3_BUCKET_NAME }} --delete

      - name: 🔄 Invalidate CloudFront cache
        if: github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/" "/work/*" "/main/*"
