# .github/workflows/commitlint.yml
name: Pull Request Commitlint

on:
  workflow_call:
jobs:
  commitlint:
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to access full commit history

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-monorepo-install
        with:
          node-version-file: ".nvmrc"

      - name: ♻️ Restore related caches
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: commitlint-tsbuildinfo-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Run commitlint on PR commits 🕵️‍♀️ Commitlint Time 🕵️‍♀️
        run: |
          yarn commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.sha }}
