name: Pull Request Audit

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize", "ready_for_review"]

concurrency:
  group: ${{ github.workflow }}-pr-audit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

jobs:
  # Skip all jobs if PR is a draft
  check-draft:
    runs-on: [ubuntu-latest]
    outputs:
      is_draft: ${{ github.event.pull_request.draft }}
    steps:
      - run: echo "PR draft status - ${{ github.event.pull_request.draft }}"

  pr-title-lint:
    needs: check-draft
    if: github.event.pull_request.draft == false
    runs-on: [ubuntu-latest]
    name: "🕵️‍♀️ Check if PR Title Follows Conventional Commit Guidelines"
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-monorepo-install
        with:
          node-version-file: ".nvmrc"

      - name: Read Node version from .nvmrc
        id: node-version
        shell: bash
        run: echo "value=$(tr -d '\r\n' < .nvmrc)" >> "$GITHUB_OUTPUT"

      - name: Lint PR title
        uses: ./.github/actions/lint-pr-title
        with:
          title: ${{ github.event.pull_request.title }}
          validator: "commitlint"
          node-version: ${{ steps.node-version.outputs.value }}

  commitlint:
    needs: check-draft
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/ci-pr-reusable-commit-lint.yml
    name: "🕵️‍♀️ Check if Commits Follow Conventional Commit Guidelines"
    secrets: inherit
  pull-request-body-audit:
    if: github.event.pull_request.draft == false
    name: "🕵️‍♀️ Check if PR Body/Descriptions Follows Guidelines"
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/audit-pr-body
