name: "Dammit I Need A New Job - CI Pull Request"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "apps/dammit-i-need-a-new-job/**"
      - "packages/**"
      - "package.json"
      - "*.lock"
      - ".yarnrc.yml"
      - "turbo.json"
      - "tsconfig.base.json"
      - ".prettier*"
      - ".github/**"
      - "!.github/workflows/ci-pr-audit.yml"
      - "!.github/workflows/ci-pr-body-audit-reusable.yml"
      - "!.github/workflows/ci-pr-reusable-commit-lint.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-build-dammit-app:
    if: github.ref != 'refs/heads/main' && github.event.pull_request.draft == false
    name: "Dammit App Tests, Build, Lint and Typecheck"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-monorepo-install
        with:
          node-version-file: ".nvmrc"

      - name: ♻️ Restore dammit app related caches
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/apps/dammit-i-need-a-new-job/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: dammit-i-need-a-new-job-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: 🕵️ Typecheck
        run: yarn turbo typecheck --filter="dammit-i-need-a-new-job..."

      - name: 🔬 Linter
        run: yarn turbo lint --filter="dammit-i-need-a-new-job..."
        env:
          TIMING: 1

      - name: 🧪 Unit tests
        run: yarn turbo test-ci --filter="dammit-i-need-a-new-job..."

      - name: 🏗 Build
        run: yarn turbo build --filter="dammit-i-need-a-new-job..."
        env:
          NEXT_TELEMETRY_DISABLED: true
