name: Reusable Terraform Workflow

on:
  workflow_call:
    inputs:
      infra-working-directory:
        description: "Location of infrastructure files"
        required: false
        type: string
        default: "./infra"

jobs:
  terraform-deploy:
    runs-on: [ubuntu-latest]
    name: Terraform Time 🧰
    environment: default
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    env:
      TF_IN_AUTOMATION: "true"
      TF_PLUGIN_CACHE_DIR: /tmp/terraform-plugin-cache
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_STATE_TOKEN }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Prepare Terraform plugin cache dir
        run: mkdir -p "${TF_PLUGIN_CACHE_DIR}"

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-tf-plugins-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.infra-working-directory)) }}
          restore-keys: |
            ${{ runner.os }}-tf-plugins-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: terraform-apply
          role-skip-session-tagging: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        working-directory: ${{ inputs.infra-working-directory }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ inputs.infra-working-directory }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ inputs.infra-working-directory }}

      - name: Plan Terraform
        id: plan
        run: |
          terraform plan -out=tfplan \
            -var="bucket_name=${{ vars.S3_BUCKET_NAME }}" \
            -var="github_owner=${{ github.repository_owner }}" \
            -var="github_repo=${{ github.event.repository.name }}"
        working-directory: ${{ inputs.infra-working-directory }}

      - name: Apply Terraform
        # TODO: Remove this once we are ready to deploy
        if: false #github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ inputs.infra-working-directory }}
